### ISSUE TITLE
[python] Package "click" has a new version which breaks linting in CI

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/cucumber-expressions#96]
### 👓 What did you see?

python CI broke on using pyflakes, I think, and in doing so, reported a traceback.

> ImportError: cannot import name '_unicodefun' from 'click'

This issue in another Python-using project describes the problem:
https://github.com/dask/distributed/issues/6013

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoa_4yao8n/py_env-python3.10/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repoa_4yao8n/py_env-python3.10/lib/python3.10/site-packages/black/__init__.py", line 1372, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repoa_4yao8n/py_env-python3.10/lib/python3.10/site-packages/black/__init__.py", line 1358, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repoa_4yao8n/py_env-python3.10/lib/python3.10/site-packages/click/__init__.py)

flake8...................................................................Passed
Error: Process completed with exit code 1.
```

### ✅ What did you expect to see?

A passing CI for Python.

### 📦 Which tool/library version are you using?

Well, this is here, in this repo, in CI.

### 🔬 How could we reproduce it?

See 
https://github.com/cucumber/cucumber-expressions/runs/5733063101?check_suite_focus=true

**Comment by olleolleolle** [comment]
@jsa34 Do you know how to fix this?
